# Power BI DAX Measures — AutoParts Intelligence Platform
# File: dashboard/dax/measures.dax
# All measures used in the 5-page Power BI dashboard

# ============================================================
# PAGE 1: EXECUTIVE OVERVIEW
# ============================================================

# Total Revenue (selected period)
Total Revenue =
CALCULATE(
    SUMX(
        fact_sales,
        fact_sales[qty_sold] * fact_sales[unit_price] * (1 - fact_sales[discount_pct] / 100)
    )
)

# Revenue vs Prior Period (YoY or MoM based on slicer)
Revenue vs Prior Period =
VAR CurrentRevenue = [Total Revenue]
VAR PriorRevenue =
    CALCULATE(
        [Total Revenue],
        DATEADD(dim_date[date], -1, YEAR)
    )
RETURN
    DIVIDE(CurrentRevenue - PriorRevenue, PriorRevenue, 0)

# Gross Profit Margin
Gross Profit Margin % =
DIVIDE(
    SUMX(fact_sales, fact_sales[gross_profit]),
    [Total Revenue],
    0
) * 100

# Total Active SKUs
Active SKU Count =
CALCULATE(
    DISTINCTCOUNT(fact_inventory[part_id]),
    dim_parts[is_active] = TRUE()
)

# Fill Rate %
Fill Rate % =
DIVIDE(
    CALCULATE(COUNTROWS(fact_sales), fact_sales[was_fulfilled] = TRUE()),
    COUNTROWS(fact_sales),
    1
) * 100

# Backorder Rate %
Backorder Rate % = 100 - [Fill Rate %]

# ============================================================
# PAGE 2: INVENTORY HEALTH
# ============================================================

# Total Inventory Value
Total Inventory Value =
SUMX(
    fact_inventory,
    fact_inventory[qty_on_hand] * fact_inventory[avg_unit_cost]
)

# Dead Stock Value
Dead Stock Value =
CALCULATE(
    [Total Inventory Value],
    FILTER(
        fact_inventory,
        DATEDIFF(fact_inventory[last_movement_date], TODAY(), DAY) > 365
    )
)

# Dead Stock % of Total
Dead Stock % =
DIVIDE([Dead Stock Value], [Total Inventory Value], 0) * 100

# Inventory Turnover Ratio (trailing 12M)
Inventory Turnover =
VAR AnnualCOGS =
    CALCULATE(
        SUM(fact_sales[cogs]),
        DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -12, MONTH)
    )
VAR AvgInventory =
    AVERAGEX(
        VALUES(dim_date[year_month]),
        CALCULATE(SUM(fact_inventory[total_stock_value]))
    )
RETURN
    DIVIDE(AnnualCOGS, AvgInventory, 0)

# Days on Hand
Days on Hand =
DIVIDE(365, [Inventory Turnover], 0)

# Stock Coverage Days (avg across all active parts)
Avg Stock Coverage Days =
AVERAGEX(
    SUMMARIZE(
        fact_inventory,
        fact_inventory[part_id],
        fact_inventory[dealer_id],
        "Coverage",
        DIVIDE(
            SUM(fact_inventory[qty_available]),
            CALCULATE(
                SUM(fact_sales[qty_sold]) / 90,
                DATESINPERIOD(dim_date[date], TODAY(), -90, DAY)
            ),
            999
        )
    ),
    [Coverage]
)

# Parts at Stockout Risk
Parts at Risk Count =
CALCULATE(
    COUNTROWS(analytics_reorder_policy),
    FILTER(
        analytics_reorder_policy,
        RELATED(fact_inventory[qty_available]) < analytics_reorder_policy[reorder_point]
    )
)

# ============================================================
# PAGE 3: DEMAND ANALYSIS
# ============================================================

# Units Sold
Total Units Sold =
SUM(fact_sales[qty_sold])

# Avg Monthly Demand (per part)
Avg Monthly Demand per Part =
DIVIDE(
    [Total Units Sold],
    DISTINCTCOUNT(fact_sales[part_id]) * 
    DATEDIFF(MIN(fact_sales[transaction_date]), MAX(fact_sales[transaction_date]), MONTH),
    0
)

# Demand Growth Rate MoM
Demand MoM Growth % =
VAR CurrentMonth = CALCULATE([Total Units Sold], DATESMTD(dim_date[date]))
VAR PriorMonth   = CALCULATE([Total Units Sold], DATEADD(DATESMTD(dim_date[date]), -1, MONTH))
RETURN DIVIDE(CurrentMonth - PriorMonth, PriorMonth, 0) * 100

# Forecast Accuracy (MAPE — lower is better)
Avg Forecast MAPE =
AVERAGE(fact_demand_forecast[mape])

# A-Class Revenue Concentration
A Class Revenue Share % =
DIVIDE(
    CALCULATE([Total Revenue], analytics_abc_xyz[abc_class] = "A"),
    [Total Revenue],
    0
) * 100

# ============================================================
# PAGE 4: SUPPLIER PERFORMANCE
# ============================================================

# On-Time Delivery Rate %
Supplier On-Time Rate % =
DIVIDE(
    CALCULATE(
        COUNTROWS(fact_purchase_orders),
        fact_purchase_orders[lead_time_delta] <= 0,
        fact_purchase_orders[po_status] = "Closed"
    ),
    CALCULATE(
        COUNTROWS(fact_purchase_orders),
        fact_purchase_orders[po_status] = "Closed"
    ),
    0
) * 100

# Average Lead Time
Avg Lead Time Days =
AVERAGEX(
    FILTER(fact_purchase_orders, fact_purchase_orders[lead_time_actual] > 0),
    fact_purchase_orders[lead_time_actual]
)

# Lead Time Variance (std dev)
Lead Time Std Dev =
STDEV.P(
    FILTER(fact_purchase_orders, fact_purchase_orders[lead_time_actual] > 0),
    fact_purchase_orders[lead_time_actual]
)

# Total PO Value
Total PO Value =
SUMX(
    fact_purchase_orders,
    fact_purchase_orders[qty_ordered] * fact_purchase_orders[unit_cost]
)

# Average Delay Days (positive = late)
Avg Delay Days =
AVERAGEX(
    FILTER(
        fact_purchase_orders,
        fact_purchase_orders[lead_time_delta] > 0
        && fact_purchase_orders[po_status] = "Closed"
    ),
    fact_purchase_orders[lead_time_delta]
)

# ============================================================
# PAGE 5: FORECASTING & REPLENISHMENT
# ============================================================

# Next Month Forecast (sum across selected parts)
Next Month Forecast Qty =
CALCULATE(
    SUM(fact_demand_forecast[forecast_qty]),
    fact_demand_forecast[forecast_date] = 
        FORMAT(EDATE(TODAY(), 1), "YYYY-MM")
)

# Replenishment Urgency Score (custom composite)
# Scale 0–100: higher = more urgent to order
Replenishment Urgency Score =
VAR CoverageScore =
    100 - MIN(DIVIDE([Avg Stock Coverage Days], 30, 0) * 100, 100)
VAR StockoutRisk =
    DIVIDE([Parts at Risk Count], [Active SKU Count], 0) * 100
RETURN
    (CoverageScore * 0.60) + (StockoutRisk * 0.40)

# Recommended Order Qty (EOQ-based)
Recommended Order Qty =
SUMX(
    FILTER(
        analytics_reorder_policy,
        RELATED(fact_inventory[qty_available]) < analytics_reorder_policy[reorder_point]
    ),
    analytics_reorder_policy[economic_order_qty]
)

# Estimated Replenishment Cost
Estimated Replenishment Cost =
SUMX(
    FILTER(
        analytics_reorder_policy,
        RELATED(fact_inventory[qty_available]) < analytics_reorder_policy[reorder_point]
    ),
    analytics_reorder_policy[economic_order_qty] * RELATED(dim_parts[standard_cost])
)
